# =============================================================================
# BrikByteOS — Coverage Collection Partial
# -----------------------------------------------------------------------------
# Task: PIPE-TEST-COVERAGE-INTEG-003
#
# Repo:
#   - Implemented in: BrikByte-Studios/.github
#
# Purpose:
#   Run the central coverage-merge.mjs script AFTER tests have generated
#   their native coverage outputs, normalize into coverage.json, and upload
#   artifacts for audit + governance.
#
# Usage (from another workflow in BrikByte-Studios/.github, *same repo*):
#
#   jobs:
#     tests:
#       # ... run tests + coverage here ...
#
#     coverage:
#       needs: tests
#       uses: BrikByte-Studios/.github/.github/workflows/partials/coverage.yml@main
#       with:
#         language: "node"
#         project-path: "node-api-example"
#
# NOTE:
#   - This partial assumes:
#       • coverage artifacts live under the given project-path
#       • .github/scripts/coverage-merge.mjs exists in repo root
# =============================================================================
name: "Partial: Coverage Collection"

on:
  workflow_call:
    inputs:
      language:
        description: "Language key for coverage normalization (node|python|java|go|dotnet)"
        required: true
        type: string
      project-path:
        description: "Relative path to the project root where coverage files live"
        required: false
        default: "."
        type: string

permissions:
  contents: read
  actions: read

jobs:
  coverage-collect:
    name: "Collect & Upload Coverage"
    runs-on: ubuntu-latest

    env:
      LANGUAGE: ${{ inputs.language }}
      PROJECT_PATH: ${{ inputs.project-path }}
      COVERAGE_OUT_PATH: "out/coverage.json"

    steps:
      # -----------------------------------------------------------------------
      # 1) Checkout repo (required for access to coverage-merge.mjs)
      # -----------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------------------------
      # 2) Setup Node.js runtime to run coverage-merge.mjs
      # -----------------------------------------------------------------------
      - name: Setup Node.js for coverage script
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # -----------------------------------------------------------------------
      # 3) Run coverage merge in the project path
      #    - Resolves native coverage formats into a single coverage.json.
      # -----------------------------------------------------------------------
      - name: Merge native coverage → coverage.json
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          set -euo pipefail

          echo "📂 Project path for coverage: ${PWD}"
          mkdir -p out

          # NOTE:
          #   coverage-merge.mjs lives at repo-root/.github/scripts.
          #   From PROJECT_PATH we reach it via ../.github/scripts.
          node ../.github/scripts/coverage-merge.mjs \
            --language "${LANGUAGE}" \
            --out "${COVERAGE_OUT_PATH}"

      # -----------------------------------------------------------------------
      # 4) Upload native coverage + normalized coverage.json as CI artifacts
      # -----------------------------------------------------------------------
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ env.LANGUAGE }}
          path: |
            ${{ env.PROJECT_PATH }}/out/coverage.json
            ${{ env.PROJECT_PATH }}/coverage/
            ${{ env.PROJECT_PATH }}/coverage.xml
            ${{ env.PROJECT_PATH }}/coverage.out
            ${{ env.PROJECT_PATH }}/target/site/jacoco/
          if-no-files-found: ignore
