# =============================================================================
# BrikByteOS — Coverage Governance Gate (Composite Action)
# -----------------------------------------------------------------------------
# Task / WBS:
#   - [TASK] GOV-TEST-COVERAGE-POLICY-004
#
# Repo:
#   - Implemented in:
#       • BrikByte-Studios/.github (.github/actions/coverage-gate)
#   - Consumed by:
#       • BrikByte-Studios/brik-pipe-examples/*
#       • Product repos
#
# Purpose:
#   Reusable composite action that enforces coverage thresholds by invoking
#   .github/scripts/coverage-check.mjs with the appropriate inputs.
# =============================================================================
name: "BrikByteOS — Coverage Governance Gate"
description: "Enforce minimum test coverage thresholds using coverage.json + .governance/tests.yml."

inputs:
  working-directory:
    description: "Directory where coverage.json lives (relative to repo root)."
    required: false
    default: "."
  coverage-file:
    description: "Path to normalized coverage.json (relative to working-directory)."
    required: false
    default: "out/coverage.json"
  policy-file:
    description: "Coverage policy file (relative to repo root)."
    required: false
    default: ".governance/tests.yml"
  baseline-file:
    description: "Optional baseline coverage file (relative to repo root)."
    required: false
    default: ".audit/coverage-baseline.json"
  node-version:
    description: "Node.js version to run the governance script with."
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1) Setup Node.js runtime for the governance script
    # -------------------------------------------------------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # -------------------------------------------------------------------------
    # 2) Run coverage governance check
    # -------------------------------------------------------------------------
    - name: Run coverage gate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        echo "🔒 [COVERAGE-GATE] Starting coverage governance check..."
        echo "🔒 [COVERAGE-GATE] Repo root          : $(git rev-parse --show-toplevel)"
        echo "🔒 [COVERAGE-GATE] Working directory  : ${PWD}"
        echo "🔒 [COVERAGE-GATE] Coverage file      : ${{ inputs.coverage-file }}"
        echo "🔒 [COVERAGE-GATE] Policy file        : ${{ inputs.policy-file }}"
        echo "🔒 [COVERAGE-GATE] Baseline file      : ${{ inputs.baseline-file }}"

        node "${GITHUB_ACTION_PATH}/coverage-check.mjs" \
          --coverage-file "${{ inputs.coverage-file }}" \
          --policy-file "${{ inputs.policy-file }}" \
          --baseline-file "${{ inputs.baseline-file }}"
