# =============================================================================
# BrikByteOS — Cache Clean Composite Action
# -----------------------------------------------------------------------------
# Task: PIPE-CACHE-STRATEGY-CONFIG-004
#
# Purpose:
#   Wraps .github/scripts/cache-clean.sh so that *other repos* (via reusable
#   workflows) can trigger cache cleanup using:
#
#     uses: BrikByte-Studios/.github/.github/actions/cache-clean@main
#
# Input:
#   paths:
#     - Newline-separated list of cache paths to delete.
#     - Example:
#         paths: |
#           ${HOME}/.npm
#           node-api-example/node_modules
#
# Behavior:
#   - Sets CACHE_PATHS env var from `paths` input.
#   - Invokes .github/scripts/cache-clean.sh.
#   - Logs clearly, never fails if a path does not exist.
# =============================================================================
name: "BrikByteOS: Cache Clean Utility"
description: >
  Central cache cleanup action for BrikByteOS pipelines, wrapping
  .github/scripts/cache-clean.sh. Supports multi-runtime cache refresh
  (Node, Python, JVM, Go, .NET, etc.).

inputs:
  paths:
    description: |
      Newline-separated list of cache directories/files to remove.
      Example:
        ${HOME}/.npm
        node-api-example/node_modules
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Run cache-clean.sh for provided paths"
      shell: bash
      env:
        CACHE_PATHS: ${{ inputs.paths }}
      run: |
        set -euo pipefail

        echo "[CACHE-CLEAN/ACTION] Invoked with paths:"
        printf '%s\n' "${CACHE_PATHS}"

        SCRIPT_PATH="${GITHUB_ACTION_PATH}/cache-clean.sh"

        if [ ! -f "${SCRIPT_PATH}" ]; then
          echo "::warning::cache-clean.sh not found at ${SCRIPT_PATH} — skipping cleanup."
          exit 0
        fi

        echo "[CACHE-CLEAN/ACTION] Executing ${SCRIPT_PATH} ..."
        bash "${SCRIPT_PATH}"
        echo "[CACHE-CLEAN/ACTION] cache-clean.sh completed."
