# -----------------------------------------------------------------------------
# BrikByteOS Pipelines — Parallel Matrix Strategy (v1)
# -----------------------------------------------------------------------------
# Purpose:
#   Defines deterministic, governed parallelization defaults for all test types.
#
# Design principles:
#   - Deterministic: no randomness, no runtime guessing
#   - Safe-by-default: conservative shard counts
#   - Cost-controlled: hard caps enforced at platform level
#   - Overridable: repos may override within allowed caps
#
# This file is consumed by:
#   - BrikPipe shared matrix-plan action
#   - All CI workflows that require governed parallel execution
# -----------------------------------------------------------------------------

version: 1

global:
  # If true, requested shard counts above caps are clamped instead of failing.
  # This prevents runaway CI costs while keeping pipelines green.
  clamp_to_caps: true

defaults:
  unit:
    # Unit tests are CPU-bound and cheap to parallelize.
    max_shards: 6      # Recommended range: 4–8
    cap: 8             # Hard upper bound

  integration:
    # Integration tests often share DBs or services.
    max_shards: 3      # Recommended range: 2–4
    cap: 4             # Hard cap to avoid contention

  e2e:
    # E2E tests are heavy and flake-prone.
    max_shards: 4      # Recommended range: 2–6
    cap: 6             # Hard cap for stability + cost
    browsers:
      - chromium
      - firefox        # Explicit list = deterministic matrix

  performance:
    # Performance tests are resource intensive.
    max_shards: 1      # Recommended range: 1–2
    cap: 2             # Hard cap

# -----------------------------------------------------------------------------
# Example override shape (NOT ACTIVE).
# Repos may copy this structure into their own override file.
# -----------------------------------------------------------------------------
overrides_example:
  unit:
    max_shards: 8
  e2e:
    browsers: [chromium, webkit]
