# BrikByte Studios — Org-wide Governance Policy (PIPE-GOV-7.1)
#
# This file defines the **baseline governance policy** for BrikByte-Studios.
# Product / service repos MAY define their own .github/policy.yml, but:
#   - They MUST conform to docs/policy/policy.schema.json
#   - They MUST NOT relax org-wide minimums
#   - They MAY tighten (stricter) rules

version: 1                     # Schema version (not policy_version)
policy_version: "1.0.0"        # Policy version (semantic versioning)
mode: "advisory"               # advisory | enforce

# ---------------------------------------------------------------------------
# REVIEWS — PIPE-GOV-7.3.1
# ---------------------------------------------------------------------------

reviews:
  # Legacy baseline (still enforced by the merge/extends logic)
  required_approvals: 2
  require_code_owner_review: true
  additional_reviewer_teams:
    - "platform-leads"

  # New standardized form
  default:
    required_approvals: 2
    require_code_owner_review: true
    required_roles: [] # None globally by default

  branches:
    main:
      required_approvals: 2
      require_code_owner_review: true

    "release/*":
      required_approvals: 2
      require_code_owner_review: true

    "hotfix/*":
      required_approvals: 2
      required_roles:
        - "platform-leads"

    "feature/*":
      required_approvals: 1
      require_code_owner_review: false

# ---------------------------------------------------------------------------
# TESTS — PIPE-GOV-7.3.2
# ---------------------------------------------------------------------------

tests:
  # Org-wide baseline coverage minimum (non-relaxable)
  coverage_min: 80

  # All tests must be green for gate to pass
  require_tests_green: true

  # Future enhancement: restrict to critical-path coverage only
  critical_paths_only: false

  # Allowed drop vs baseline in percentage points
  coverage_delta_min: -2

  # Location of test coverage summary artifact (relative to repo root)
  coverage_report_path: "coverage/coverage-summary.json"

# ---------------------------------------------------------------------------
# SECURITY — PIPE-GOV-7.3.3
# ---------------------------------------------------------------------------

security:
  sast:
    tool: "codeql"                        # or "semgrep"
    max_severity: "medium"                # no high/critical allowed unless waived
    report_path: "reports/codeql-results.json"

  sca:
    tool: "npm-audit"                     # or pip-audit, mvn-dependency-check
    max_severity: "high"                  # critical only allowed via waiver
    report_path: "reports/npm-audit.json"

# ---------------------------------------------------------------------------
# DOCUMENTATION GOVERNANCE
# ---------------------------------------------------------------------------

docs:
  require_docs_on_feature_change: true
  paths:
    - "docs/**"
    - "ADR/**"
    - "adr/**"
    - "docs/adr/**"

# ---------------------------------------------------------------------------
# SUPPLY CHAIN — Release integrity, SBOMs, signatures
# ---------------------------------------------------------------------------

supply_chain:
  require_signed_artifacts: true
  require_sbom: true


adr:
  # Paths where changes *usually* require ADRs
  required_on_paths:
    - "infra/**"
    - ".github/**"
    - "charts/**"
    - "security/**"

  # If true, ADRs referenced in PRs must have status: Accepted
  require_accepted_adr: true

  # Glob used by ADR tooling to find ADR files
  adr_file_glob: "docs/adr/[0-9][0-9][0-9]-*.md"


artifacts:
  require_sbom: true
  require_hashes: true
  require_signatures: true

  # Hash algorithm used when generating manifest entries.
  hash_algorithm: "sha256"

  # Where SBOM and hash manifests are expected to be found.
  sbom_path: "artifacts/sbom.spdx.json"
  hashes_manifest_path: "artifacts/manifest.json"

  # Signature verification expectations.
  signature:
    tool: "cosign"
    verify_subject: "BrikByte-Studios"
    # JSON status file generated by prior CI step:
    status_path: "artifacts/signature-status.json"


# ---------------------------------------------------------------------------
# WAIVERS — explicit, time-bound, auditable
# ---------------------------------------------------------------------------

waivers:
  # EXAMPLE (keep or remove)
  - rule: "security.sca"
    scope: "CVE-2025-12345"
    reason: "Vendor patch not yet available; WAF rule in place"
    ttl: "2025-12-31"
    approver: "@security-lead"
    evidence: "https://internal/wiki/waivers/CVE-2025-12345"
