#!/usr/bin/env bash
# BrikPipe — Integration Environment Generator
# --------------------------------------------
# Purpose:
#   Build a safe, runtime `.env.integ.runtime` file for integration tests
#   based on INTEG_* environment variables injected from GitHub Environments
#   and Secrets.
#
#   - Fails fast if required INTEG_* secrets are missing.
#   - Uses GitHub ::add-mask:: to redact sensitive values from logs.
#   - Supports local developer overrides via .env.integ.local (gitignored).
#
# Usage (CI):
#   # In GitHub Actions, with secrets mapped to INTEG_* env vars:
#   SERVICE_WORKDIR="node-api-example" \
#   .github/scripts/env-generate-integration.sh
#
# Usage (local dev):
#   # Export INTEG_* vars OR create .env.integ.local, then:
#   SERVICE_WORKDIR="node-api-example" \
#   ./github/scripts/env-generate-integration.sh
#
# Environment:
#   SERVICE_WORKDIR        : Service directory (default: .)
#   OUTPUT_FILE            : Target file name (default: .env.integ.runtime)
#   LOCAL_OVERRIDE_FILE    : Local override file (default: .env.integ.local)
#
# Required INTEG_* variables (initial set):
#   INTEG_DB_USER
#   INTEG_DB_PASS
#   INTEG_DB_NAME
#   INTEG_DB_HOST
#   INTEG_DB_PORT
#   JWT_SECRET_TEST

set -euo pipefail

log() {
  # log LEVEL MESSAGE...
  local level="$1"
  shift
  printf '[ENVGEN-%s] %s\n' "${level}" "$*"
}

# ------------------------------------------------------------------
# 1. Resolve paths and configuration
# ------------------------------------------------------------------
SERVICE_WORKDIR="${SERVICE_WORKDIR:-.}"
OUTPUT_FILE="${OUTPUT_FILE:-.env.integ.runtime}"
LOCAL_OVERRIDE_FILE="${LOCAL_OVERRIDE_FILE:-.env.integ.local}"

cd "${SERVICE_WORKDIR}"

OUTPUT_PATH="${OUTPUT_FILE}"
LOCAL_OVERRIDE_PATH="${LOCAL_OVERRIDE_FILE}"

log "INFO" "Service workdir         : ${SERVICE_WORKDIR}"
log "INFO" "Runtime env output file : ${OUTPUT_PATH}"
log "INFO" "Local override file     : ${LOCAL_OVERRIDE_PATH} (optional)"

# ------------------------------------------------------------------
# 2. Define required secrets
# ------------------------------------------------------------------
# NOTE:
#   Extend this list as we standardize more integration secrets.
#   All must follow the INTEG_* naming convention.
REQUIRED_VARS=(
  "INTEG_DB_USER"
  "INTEG_DB_PASS"
  "INTEG_DB_NAME"
  "INTEG_DB_HOST"
  "INTEG_DB_PORT"
  "JWT_SECRET_TEST"
)

# ------------------------------------------------------------------
# 3. Validate presence of required INTEG_* secrets
# ------------------------------------------------------------------
missing=0
for var in "${REQUIRED_VARS[@]}"; do
  value="${!var-}"

  if [[ -z "${value}" ]]; then
    log "ERROR" "Missing required integration secret: ${var}"
    missing=$((missing + 1))
  fi
done

if (( missing > 0 )); then
  log "ERROR" "Found ${missing} missing required INTEG_* secrets. Failing fast."
  echo "::error::Missing required integration secrets. Check GitHub Environment 'integration' and Org/Repo secrets."
  exit 1
fi

# ------------------------------------------------------------------
# 4. Mask sensitive values in GitHub logs
# ------------------------------------------------------------------
# GitHub will redact any string passed to ::add-mask:: from logs.
for var in "${REQUIRED_VARS[@]}"; do
  value="${!var-}"
  if [[ -n "${value}" ]]; then
    echo "::add-mask::${value}"
  fi
done

# ------------------------------------------------------------------
# 5. Generate base .env.integ.runtime file
# ------------------------------------------------------------------
log "INFO" "Generating ${OUTPUT_PATH} from INTEG_* environment variables..."

# NOTE:
#   - This file MUST NOT be committed.
#   - It is safe to mount as --env-file into integration test containers.
cat > "${OUTPUT_PATH}" <<EOF
# Auto-generated by env-generate-integration.sh
# DO NOT COMMIT. DO NOT CHECK IN.
#
# Base integration runtime environment derived from INTEG_* secrets.

# Database (integration)
DB_USER=${INTEG_DB_USER}
DB_PASS=${INTEG_DB_PASS}
DB_NAME=${INTEG_DB_NAME}
DB_HOST=${INTEG_DB_HOST}
DB_PORT=${INTEG_DB_PORT}

# Test-only JWT secret (non-production)
JWT_SECRET=${JWT_SECRET_TEST}
EOF

log "INFO" "Base runtime env file created at: ${OUTPUT_PATH}"

# ------------------------------------------------------------------
# 6. Apply local overrides (developer only, optional)
# ------------------------------------------------------------------
if [[ -f "${LOCAL_OVERRIDE_PATH}" ]]; then
  log "INFO" "Applying local overrides from ${LOCAL_OVERRIDE_PATH} (developer only)..."
  {
    echo ""
    echo "# --- Local developer overrides (last-wins) ---"
    cat "${LOCAL_OVERRIDE_PATH}"
  } >> "${OUTPUT_PATH}"
  log "INFO" "Local overrides appended to ${OUTPUT_PATH}"
else
  log "INFO" "No local override file found (${LOCAL_OVERRIDE_PATH}); skipping."
fi

log "INFO" "Integration env generation complete."
exit 0
