# BrikByteOS — Node Dependency Cache (npm / Yarn Berry / pnpm)
# ---------------------------------------------------------------------------
# PIPE-CACHE-NODE-BUILD-001 + ENHANCED (project-path support)
#
# New Feature:
#   ✔ Supports `project-path` — detects lockfiles inside target folder
#   ✔ Cache key now hashes lockfiles inside project-path
#   ✔ Safe defaults maintained for monorepos / multi-app repos
# ---------------------------------------------------------------------------

name: "Cache Node Dependencies (npm / Yarn / pnpm) — project aware"
description: >
  BrikByteOS composite action to cache Node dependencies across npm, Yarn Berry, and pnpm.
  Supports monorepos via project-path detection.

inputs:
  node-version:
    description: "Node version (must match setup-node version)."
    required: true

  project-path:
    description: "Where package.json + lockfiles live. Supports monorepo apps."
    required: false
    default: "."   # root fallback

runs:
  using: "composite"
  steps:
    # -----------------------------------------------------------------------
    # 1) Detect package manager based on lockfiles inside project-path
    # -----------------------------------------------------------------------
    - name: "Detect Node package manager"
      id: detect
      shell: bash
      working-directory: ${{ inputs.project-path }}
      run: |
        set -euo pipefail

        manager="npm"
        cache_path="${HOME}/.npm"

        if [ -f "pnpm-lock.yaml" ]; then
          manager="pnpm"
          cache_path="${HOME}/.local/share/pnpm/store"
        elif [ -f "yarn.lock" ]; then
          manager="yarn"
          cache_path=".yarn/cache"
        elif [ -f "package-lock.json" ]; then
          manager="npm"
          cache_path="${HOME}/.npm"
        else
          echo "::notice::No lockfile found in '${PWD}', defaulting to npm ~/.npm cache"
        fi

        echo "manager=${manager}"     >> "$GITHUB_OUTPUT"
        echo "cache-path=${cache_path}" >> "$GITHUB_OUTPUT"
        echo "::notice::Detected Node manager='${manager}' at path='${PWD}'"

    # -----------------------------------------------------------------------
    # 2) Cache Dependencies — key includes lockfile hash inside project-path
    # -----------------------------------------------------------------------
    - name: "Cache Node deps"
      id: cache-node
      uses: actions/cache@v4
      with:
        path: ${{ steps.detect.outputs.cache-path }}
        key: >
          node-${{ runner.os }}-${{ inputs.node-version }}-${{ steps.detect.outputs.manager }}-${{
          hashFiles(
            format('{0}/package-lock.json', inputs['project-path']),
            format('{0}/yarn.lock', inputs['project-path']),
            format('{0}/pnpm-lock.yaml', inputs['project-path'])
          ) }}
        restore-keys: |
          node-${{ runner.os }}-${{ inputs.node-version }}-${{ steps.detect.outputs.manager }}-

    # -----------------------------------------------------------------------
    # 3) Summarize Cache Result in Logs
    # -----------------------------------------------------------------------
    - name: "Cache Summary"
      shell: bash
      run: |
        if [ "${{ steps.cache-node.outputs.cache-hit }}" = "true" ]; then
          echo "🚀 Cache restored successfully for ${{
            steps.detect.outputs.manager
          }} (Node v${{ inputs.node-version }})"
        else
          echo "🆕 Cache created for ${{
            steps.detect.outputs.manager
          }} (Node v${{ inputs.node-version }})"
        fi
