name: "BrikByteOS — Unit Test Audit Export"
description: >
  Export unit test audit bundle (.audit/<timestamp>/unit-tests) containing
  JUnit results, coverage summary, and CI metadata for governance and compliance.
author: "BrikByte Studios"

inputs:
  working-directory:
    description: "Directory where JUnit, coverage.json, and .audit/ live (relative to repo root)"
    required: false
    default: "."
  junit:
    description: "Path to JUnit XML file, relative to working-directory"
    required: false
    default: "out/junit.xml"
  coverage:
    description: "Path to normalized coverage.json file, relative to working-directory"
    required: false
    default: "out/coverage.json"
  audit-root:
    description: "Root directory for audit bundles (relative to working-directory)"
    required: false
    default: ".audit"
  runtime:
    description: "Runtime descriptor (e.g. node@20, python@3.11, dotnet@8.0)"
    required: false
    default: ""
  duration-seconds:
    description: "Optional duration (in seconds) for the unit test run"
    required: false
    default: ""
  node-version:
    description: "Node.js version to use for the exporter script"
    required: false
    default: "20"

  # ---------------------------------------------------------------------------
  # Artifact upload controls
  # ---------------------------------------------------------------------------
  upload-artifact:
    description: >
      If 'true', upload the audit root directory (.audit/) as a GitHub
      Actions artifact after export-unit-audit.mjs finishes.
    required: false
    default: "true"

  artifact-name:
    description: >
      Optional override for the artifact name. If empty, a default name
      including job + run_attempt will be used.
    required: false
    default: ""

  # ---------------------------------------------------------------------------
  # Future blob sync hook (no external upload yet)
  # ---------------------------------------------------------------------------
  upload-to-blob:
    description: >
      If 'true', invoke a stub blob-sync hook. This does NOT perform any real
      external upload yet, but is a safe extension point for future tasks
      (e.g. sync to S3 / Azure Blob / GCS).
    required: false
    default: "false"

  blob-target:
    description: >
      Logical blob destination identifier, e.g. 's3://brikbyte-audit/unit-tests'
      or 'azure://brikbyte-audit/unit-tests'. Currently used only for logging.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1) Setup Node.js runtime for the exporter script
    # -------------------------------------------------------------------------
    - name: Setup Node.js for audit exporter
      # BrikByte-Studios/.github/.github/actions/audit-export is consumed
      # by repos like:
      #   - BrikByte-Studios/brik-pipe-examples
      #   - Product repos using BrikByteOS test templates
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # -------------------------------------------------------------------------
    # 2) Run the audit exporter script
    #    - Script is co-located in this action directory:
    #      ${GITHUB_ACTION_PATH}/export-unit-audit.mjs
    # -------------------------------------------------------------------------
    - name: Export unit test audit bundle
      shell: bash
      run: |
        set -euo pipefail

        echo "[COVERAGE-AUDIT/ACTION] Working directory  : '${{ inputs.working-directory }}'"
        echo "[COVERAGE-AUDIT/ACTION] JUnit path         : '${{ inputs.junit }}'"
        echo "[COVERAGE-AUDIT/ACTION] Coverage path      : '${{ inputs.coverage }}'"
        echo "[COVERAGE-AUDIT/ACTION] Audit root         : '${{ inputs.audit-root }}'"
        echo "[COVERAGE-AUDIT/ACTION] Runtime            : '${{ inputs.runtime }}'"
        echo "[COVERAGE-AUDIT/ACTION] Duration (seconds) : '${{ inputs.duration-seconds }}'"

        cd "${{ inputs.working-directory }}"

        EXTRA_ARGS=""
        if [ -n "${{ inputs.duration-seconds }}" ]; then
          EXTRA_ARGS="--duration-seconds \"${{ inputs.duration-seconds }}\""
        fi

        # Delegates all parsing / JSON construction to export-unit-audit.mjs.
        # That script:
        #   • Parses JUnit XML -> results.json
        #   • Distils coverage.json -> coverage-summary.json
        #   • Creates metadata.json from GitHub env + CLI args
        #   • Writes into: <audit-root>/<timestamp>/unit-tests/
        node "${GITHUB_ACTION_PATH}/export-unit-audit.mjs" \
          --junit "${{ inputs.junit }}" \
          --coverage "${{ inputs.coverage }}" \
          --audit-root "${{ inputs.audit-root }}" \
          --runtime "${{ inputs.runtime }}" \
          $EXTRA_ARGS

    # -------------------------------------------------------------------------
    # 3) Always upload .audit/ as artifact (unless explicitly disabled)
    # -------------------------------------------------------------------------
    - name: Upload .audit bundle as artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        # If caller provided a name, honour it; otherwise derive a stable one.
        name: ${{ inputs.artifact-name != '' && inputs.artifact-name || format('unit-tests-audit-{0}-{1}', github.job, github.run_attempt) }}
        # Upload the entire audit root for this repo/project.
        # Using ** ensures nested timestamp folders are included.
        path: |
          ${{ inputs.working-directory }}/${{ inputs.audit-root }}/**
        include-hidden-files: true      # REQUIRED (because .audit is hidden)
        if-no-files-found: ignore       # RECOMMENDED
        compression-level: 6
        overwrite: false

    # -------------------------------------------------------------------------
    # 4) Stub blob-sync hook (no external upload yet)
    #
    #    This is intentionally a no-op for now. It gives governance / infra
    #    teams a clear extension point:
    #
    #      - They can add a follow-up task to:
    #          • Configure cloud credentials via secrets
    #          • Implement a sync script (e.g. .github/scripts/audit-blob-sync.mjs)
    #          • Invoke that script here when `upload-to-blob: true`
    #
    #    For now we only log intent safely.
    # -------------------------------------------------------------------------
    - name: Blob sync hook (stub only — no external upload)
      if: ${{ inputs.upload-to-blob == 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        echo "[COVERAGE-AUDIT/ACTION] upload-to-blob = TRUE"
        echo "[COVERAGE-AUDIT/ACTION] Invoking stub blob-sync script..."

        node "${GITHUB_ACTION_PATH}/audit-blob-sync.mjs" \
          --audit-root "${{ inputs.audit-root }}" \
          --blob-target "${{ inputs.blob-target }}"
