name: "BrikPipe Matrix Plan"
description: >
  Computes a deterministic, governed GitHub Actions matrix
  based on BrikByteOS parallelization rules.

inputs:
  test_type:
    description: "Test category: unit | integration | e2e | performance"
    required: true

  config_path:
    description: >
      Optional path to parallel-matrix.yml in the caller repo.
      If empty, defaults to the action-bundled config.
    required: false
    default: ""

  override_shards:
    description: >
      Optional requested shard count.
      Will be clamped to configured cap.
    required: false
    default: ""

  browsers:
    description: >
      Optional comma-separated browser list (E2E only).
      Must be deterministic (explicit names).
    required: false
    default: ""

  items:
    description: >
      Optional comma-separated list of scenario/service IDs.
      Used for integration/performance grouping.
    required: false
    default: ""
  
  # NEW (integration)
  services_csv:
    required: false
    default: ""
  scenarios_csv:
    required: false
    default: ""

outputs:
  matrix_json:
    description: "JSON string to be used as strategy.matrix"
    value: ${{ steps.plan.outputs.matrix_json }}

runs:
  using: "composite"
  steps:
    - name: "Generate deterministic matrix"
      id: plan
      shell: bash
      run: |
        set -euo pipefail

        # If caller did not provide a config path, use the action-bundled config.
        CONFIG_PATH="${{ inputs.config_path }}"
        if [[ -z "${CONFIG_PATH}" ]]; then
          CONFIG_PATH="${{ github.action_path }}/parallel-matrix.yml"
        fi

        echo "[MATRIX-PLAN] test_type=${{ inputs.test_type }}"
        echo "[MATRIX-PLAN] config_path=${CONFIG_PATH}"
        echo "[MATRIX-PLAN] override_shards=${{ inputs.override_shards }}"
        echo "[MATRIX-PLAN] browsers=${{ inputs.browsers }}"
        echo "[MATRIX-PLAN] items=${{ inputs.items }}"
        echo "[MATRIX-PLAN] services_csv=${{ inputs.services_csv }}"
        echo "[MATRIX-PLAN] scenarios_csv=${{ inputs.scenarios_csv }}"

        ruby "${{ github.action_path }}/matrix_plan.rb" \
          "${{ inputs.test_type }}" \
          "${CONFIG_PATH}" \
          "${{ inputs.override_shards }}" \
          "${{ inputs.browsers }}" \
          "${{ inputs.items }}" \
          "${{ inputs.services_csv }}" \
          "${{ inputs.scenarios_csv }}"
