# -----------------------------------------------------------------------------
# BrikByteOS Pipelines — Parallel Matrix Strategy (v1)
# -----------------------------------------------------------------------------
# Purpose:
#   Defines deterministic, governed parallelization defaults for all test types.
#
# Design principles:
#   - Deterministic: no randomness, no runtime guessing
#   - Safe-by-default: conservative shard counts
#   - Cost-controlled: hard caps enforced at platform level
#   - Overridable: repos may override within allowed caps
#
# This file is consumed by:
#   - BrikPipe shared matrix-plan action
#   - All CI workflows that require governed parallel execution
# -----------------------------------------------------------------------------

version: 1

global:
  clamp_to_caps: true
  min_shards: 1

defaults:
  unit:
    default_shards: 6
    max_shards: 8

  integration:
    default_shards: 3
    max_shards: 4

  e2e:
    default_shards: 4
    max_shards: 6
    browsers:
      - chromium
      - firefox

  performance:
    default_shards: 1
    max_shards: 2

overrides_example:
  unit:
    default_shards: 8
  e2e:
    browsers: [chromium, webkit]
