name: "🐞 Bug Report"
description: Report a reproducible defect
title: "[Bug]: <brief>"
labels: ["bug"]
assignees: ["qa"]
body:
  - type: textarea
    id: env
    attributes: { label: Environment, description: "App, version, OS/browser" }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to Reproduce, description: "1… 2… 3…" }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected Result }
    validations: { required: true }
  - type: textarea
    id: actual
    attributes: { label: Actual Result }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs/Screenshots }
