name: "🐞 Bug Report"
description: "Report a defect so we can triage, reproduce, and fix it efficiently."
title: "[BUG] <short summary>"
labels:
  - "type:bug"
  - "status:triage"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.

        The more precise you are, the faster we can fix it.

        🔐 Remove or mask any sensitive data (keys, tokens, personal data).

  # -------------------------------------------------------
  # 1️⃣ Executive Summary & Business Context
  # -------------------------------------------------------

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Short, clear description of the defect."
      placeholder: "e.g., Cannot submit payment form when selecting Ozow on mobile."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Business Impact"
      placeholder: |
        Affected users/tenants:
        Revenue impact:
        Operational impact:
        Customer-visible? (Y/N):
        Release-blocking? (Y/N):
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity (S*)"
      options:
        - "S0 - Critical (data loss, security breach, system down)"
        - "S1 - High (core flow broken; no workaround)"
        - "S2 - Medium (workaround exists)"
        - "S3 - Low (cosmetic / minor edge case)"
    validations:
      required: true

  - type: dropdown
    id: data_integrity
    attributes:
      label: "Data Integrity Impact"
      options:
        - "No data impact"
        - "Incorrect data displayed"
        - "Incorrect data stored"
        - "Data corruption risk"
        - "Data loss occurred"
    validations:
      required: true

  - type: dropdown
    id: security_impact
    attributes:
      label: "Security / Compliance Impact"
      options:
        - "None"
        - "Potential sensitive data exposure"
        - "Auth/RBAC bypass"
        - "Compliance risk (POPIA/GDPR/etc.)"
        - "Confirmed security incident"
    validations:
      required: true

  # -------------------------------------------------------
  # 2️⃣ Frequency & Blast Radius
  # -------------------------------------------------------

  - type: dropdown
    id: frequency
    attributes:
      label: "Frequency"
      options:
        - "Every time"
        - "Often"
        - "Sometimes"
        - "Rare"
        - "Unable to reproduce consistently"
    validations:
      required: true

  - type: textarea
    id: blast_radius
    attributes:
      label: "Blast Radius"
      placeholder: |
        Scope of impact:
        - Single tenant?
        - All tenants?
        - Region-specific?
        - Specific feature flag?
    validations:
      required: true

  # -------------------------------------------------------
  # 3️⃣ Environment & Versioning
  # -------------------------------------------------------

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      options:
        - "Production"
        - "Staging / UAT"
        - "QA"
        - "Development"
        - "Local"
    validations:
      required: true

  - type: input
    id: product_area
    attributes:
      label: "Product / Repo / Area"
      placeholder: "proj/brikbyteos • area:billing"
    validations:
      required: true

  - type: input
    id: version_build
    attributes:
      label: "Version / Build / Tag"
      placeholder: "v2.1.0 (build 2310)"
    validations:
      required: false

  - type: input
    id: commit_sha
    attributes:
      label: "Commit SHA (if known)"
      placeholder: "abc123def"
    validations:
      required: false

  - type: input
    id: observed_at
    attributes:
      label: "Date / Time Observed (UTC)"
      placeholder: "2026-02-25T14:30:00Z"
    validations:
      required: false

  - type: input
    id: correlation_id
    attributes:
      label: "Correlation / Request ID (if available)"
      placeholder: "x-request-id: 12ab34cd"
    validations:
      required: false

  # -------------------------------------------------------
  # 4️⃣ Reproduction
  # -------------------------------------------------------

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: "Regression?"
      options:
        - "Yes (previously working)"
        - "No (newly discovered behavior)"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: regression_details
    attributes:
      label: "If regression, last known working version/date"
    validations:
      required: false

  # -------------------------------------------------------
  # 5️⃣ Workaround & Urgency
  # -------------------------------------------------------

  - type: textarea
    id: workaround
    attributes:
      label: "Workaround (if any)"
      placeholder: |
        Temporary mitigation steps:
        - Disable feature flag
        - Manual intervention
        - Retry strategy
    validations:
      required: false

  - type: dropdown
    id: hotfix_required
    attributes:
      label: "Hotfix Required?"
      options:
        - "Yes — immediate patch required"
        - "No — can wait for next sprint"
        - "Unsure"
    validations:
      required: true

  # -------------------------------------------------------
  # 6️⃣ Diagnostics & Evidence
  # -------------------------------------------------------

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Diagnostics (sanitized)"
      render: shell
      placeholder: |
        Server logs:
        Stack trace:
        HTTP status:
        DB errors:
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / Recordings"
    validations:
      required: false

  - type: textarea
    id: feature_flags
    attributes:
      label: "Feature Flags / Config"
      placeholder: |
        feature.x = enabled
        ENV_MODE = prod
    validations:
      required: false

  - type: textarea
    id: suspected_cause
    attributes:
      label: "Suspected Cause (optional)"
    validations:
      required: false

  # -------------------------------------------------------
  # 7️⃣ Governance & Traceability
  # -------------------------------------------------------

  - type: textarea
    id: related_refs
    attributes:
      label: "Related Requirements / Test Cases / Incidents"
      placeholder: |
        REQ-*
        TC-*
        Incident-*
        RTM row:
    validations:
      required: false

  # -------------------------------------------------------
  # 8️⃣ Reporter Metadata
  # -------------------------------------------------------

  - type: input
    id: reporter_role
    attributes:
      label: "Reporter Role"
      placeholder: "QA • Support • Customer • Dev"
    validations:
      required: false

  # -------------------------------------------------------
  # 9️⃣ Pre-Flight Validation
  # -------------------------------------------------------

  - type: checkboxes
    id: preflight
    attributes:
      label: "Pre-Flight Checklist"
      options:
        - label: "I searched for duplicates."
          required: true
        - label: "Steps to reproduce are clear and deterministic."
          required: true
        - label: "Logs/screenshots are sanitized."
          required: true
        - label: "I verified this is not local-only misconfiguration."
          required: false