name: "✨ Feature Request"
description: "Propose a new feature or enhancement for a BrikByte product."
title: "[FEAT] <short summary>"
labels:
  - "type:feature"
  - "status:triage"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature for BrikByte Studios 👋

        This form captures **problem**, **value**, **scope**, and **delivery intent** so we can:
        triage → prioritize → design → implement → measure success.

        🔐 Do not include secrets, credentials, or personal information.

  # -------------------------------------------------------
  # 1) Executive Summary (fast triage)
  # -------------------------------------------------------
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "One paragraph: what you want + why it matters."
      placeholder: |
        What capability is requested?
        Who benefits?
        What outcome improves?
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: "Request Type"
      options:
        - "New feature"
        - "Enhancement of existing feature"
        - "Technical capability / platform feature"
        - "Experiment / A/B test"
        - "Other"
    validations:
      required: true

  # -------------------------------------------------------
  # 2) Product Context (where it lives)
  # -------------------------------------------------------
  - type: input
    id: product_area
    attributes:
      label: "Product / Repo / Area"
      description: "Use BrikByte taxonomy where possible."
      placeholder: "CargoPulse Web • proj/cargopulse • area:shipments"
    validations:
      required: true

  - type: textarea
    id: target_users
    attributes:
      label: "Primary Users / Personas"
      placeholder: |
        - Persona(s):
        - Tenants / markets:
        - Internal vs external:
    validations:
      required: true

  # -------------------------------------------------------
  # 3) Problem Framing (the ‘why’)
  # -------------------------------------------------------
  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem / Opportunity"
      description: "Describe pain and consequences. Avoid prescribing a solution."
      placeholder: |
        Current situation:
        Pain / friction:
        Who is impacted:
        What happens if we do nothing:
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: "Evidence (if available)"
      description: "Attach proof: tickets, analytics, user quotes, screenshots, competitor links."
      placeholder: |
        - Support ticket volume:
        - Customer quotes:
        - Funnel drop-off:
        - Incident / escalations:
        - Competitor reference:
    validations:
      required: false

  # -------------------------------------------------------
  # 4) Use Cases (what users actually do)
  # -------------------------------------------------------
  - type: textarea
    id: user_story
    attributes:
      label: "User Story / Use Cases"
      placeholder: |
        As a <role>,
        I want <capability>,
        So that <value>.

        Use cases:
        1)
        2)
        3)
    validations:
      required: true

  # -------------------------------------------------------
  # 5) Business Value (why we prioritize it)
  # -------------------------------------------------------
  - type: textarea
    id: business_value
    attributes:
      label: "Business Value & Outcomes"
      placeholder: |
        Business drivers:
        Expected impact (revenue/cost/risk/NPS/retention):
        Who is asking (customer/internal/regulatory):
        Time sensitivity / deadline:
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: "Impact"
      options:
        - "High — major revenue/risk reduction/core capability"
        - "Medium — meaningful improvement"
        - "Low — small/localized improvement"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority (triage signal)"
      options:
        - "P0 — Must do now (deadline / production risk)"
        - "P1 — High"
        - "P2 — Medium"
        - "P3 — Low / backlog"
    validations:
      required: true

  - type: dropdown
    id: confidence
    attributes:
      label: "Confidence in value"
      description: "How sure are we this will produce the intended outcome?"
      options:
        - "High — data-backed / customer committed"
        - "Medium — strong hypothesis"
        - "Low — speculative / needs discovery"
    validations:
      required: true

  # -------------------------------------------------------
  # 6) Scope Control (stop scope creep)
  # -------------------------------------------------------
  - type: textarea
    id: scope
    attributes:
      label: "Scope (In / Out / Assumptions)"
      placeholder: |
        In scope:
        - UI:
        - API:
        - Data/reporting:
        - Integrations:

        Out of scope / non-goals:
        - ...

        Assumptions:
        - ...

        Constraints (time, legal, platform):
        - ...
    validations:
      required: true

  # -------------------------------------------------------
  # 7) Acceptance Criteria (binary + testable)
  # -------------------------------------------------------
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Testable conditions for ‘done’."
      placeholder: |
        - [ ] Given <context>, when <action>, then <expected outcome>.
        - [ ] Negative: when <bad input>, system <fails safely>.
        - [ ] Permissions/RBAC: <who can do what>.
        - [ ] Backward compatibility preserved (if applicable).
    validations:
      required: true

  - type: textarea
    id: non_functional_requirements
    attributes:
      label: "Non-Functional Requirements (NFRs)"
      placeholder: |
        Performance:
        Security/Privacy (POPIA/GDPR):
        Reliability (flags, rollback, idempotency):
        UX/Accessibility:
        Observability/monitoring expectations:
    validations:
      required: false

  # -------------------------------------------------------
  # 8) Delivery & Measurement (ship + prove)
  # -------------------------------------------------------
  - type: textarea
    id: rollout_plan
    attributes:
      label: "Rollout & Release Strategy"
      placeholder: |
        Feature flag name:
        Phased rollout / beta cohort:
        Migration/backfill (if any):
        Rollback plan:
    validations:
      required: false

  - type: textarea
    id: success_metrics
    attributes:
      label: "Success Metrics & Measurement Plan"
      description: "How we’ll know it worked (and where we’ll measure it)."
      placeholder: |
        Leading metrics (adoption, activation, time-on-task):
        Lagging metrics (revenue, churn, tickets):
        Tracking requirements (events, properties):
        Dashboards/alerts to add:
        Baseline today:
        Target after launch:
    validations:
      required: false

  - type: textarea
    id: telemetry_requirements
    attributes:
      label: "Telemetry Requirements (preferred)"
      description: "Define events/logs/metrics needed as part of ‘done’."
      placeholder: |
        Events to emit:
        - event_name:
          props:

        Metrics:
        Logs (PII-safe):
        Traces (span names):
    validations:
      required: false

  # -------------------------------------------------------
  # 9) Dependencies / Governance (enterprise hooks)
  # -------------------------------------------------------
  - type: textarea
    id: dependencies_rel
    attributes:
      label: "Dependencies & Relationships"
      placeholder: |
        Depends on:
        Impacts:
        Related issues/epics:
        External vendors/systems:
    validations:
      required: false

  - type: textarea
    id: governance
    attributes:
      label: "Governance / Traceability"
      placeholder: |
        Requirements / RTM:
        ADR needed? (Y/N) If yes, why:
        Compliance considerations:
        Audit/evidence needs:
    validations:
      required: false

  # -------------------------------------------------------
  # 10) Solution Notes (optional — keep non-binding)
  # -------------------------------------------------------
  - type: textarea
    id: design_ideas
    attributes:
      label: "Design Notes / Proposed Approach (optional)"
      description: "Helpful hints only; final design may differ."
      placeholder: |
        UX notes / Figma link:
        API shape ideas:
        Data model thoughts:
        Feature flag/config:
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      placeholder: |
        Alternative 1:
        Alternative 2:
        Why this proposal is preferred:
    validations:
      required: false

  - type: textarea
    id: risks_constraints
    attributes:
      label: "Risks, Constraints & Open Questions"
      placeholder: |
        Risks:
        Constraints:
        Open questions:
    validations:
      required: false

  - type: textarea
    id: mitigations
    attributes:
      label: "Mitigations / Safeguards"
      placeholder: |
        Feature flag:
        Canary:
        Rate limits:
        Validation/testing strategy:
        Observability:
        Contingency (rollback/off-switch):
    validations:
      required: false

  # -------------------------------------------------------
  # 11) Reporter Metadata & Preflight
  # -------------------------------------------------------
  - type: input
    id: reporter_role
    attributes:
      label: "Your Role / Team"
      placeholder: "Product • QA • Customer • Support • Engineering"
    validations:
      required: false

  - type: checkboxes
    id: preflight
    attributes:
      label: "Pre-Flight Checklist"
      options:
        - label: "I searched existing issues to avoid duplicates."
          required: true
        - label: "Problem + business value are clear (not just the solution)."
          required: true
        - label: "Acceptance criteria are included and testable."
          required: true
        - label: "Scope includes explicit non-goals to prevent creep."
          required: true
        - label: "No secrets, credentials, or personal data included."
          required: true