name: "🚨 Incident (SRE)"
description: "Record a production or critical environment incident with full SRE context."
title: "[INCIDENT] <short summary>"
labels:
  - "type:incident"
  - "area:sre"
  - "status:triage"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for recording an incident for BrikByte Studios 👋

        This template is for **SRE-grade incident tracking**:
        - Clear impact & severity
        - Accurate timeline (UTC)
        - SLO/SLA impact + error budget notes
        - Mitigation vs root-cause fix separation
        - Follow-up actions that prevent recurrence

        🔐 Do not include secrets, credentials, or personal information. Sanitize logs/payloads.

  # -------------------------------------------------------
  # 1) Summary & Classification
  # -------------------------------------------------------
  - type: input
    id: summary
    attributes:
      label: "Incident Summary"
      placeholder: "e.g., Checkout failures for ZA tenants due to payment gateway timeouts."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity (SEV-*)"
      options:
        - "SEV-0 - Critical (full outage / safety / major data loss / active security incident)"
        - "SEV-1 - High (major degradation; core flows severely impacted)"
        - "SEV-2 - Medium (partial degradation; workarounds exist)"
        - "SEV-3 - Low (minor impact / edge cases)"
        - "SEV-4 - Informational / Near miss"
    validations:
      required: true

  - type: dropdown
    id: impact_type
    attributes:
      label: "Impact Type"
      options:
        - "Availability / Outage"
        - "Performance Degradation"
        - "Functional Error / Incorrect Behaviour"
        - "Data Quality / Data Loss (non-PII)"
        - "Security / Privacy (also raise via security process)"
        - "Operational / Process"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Incident Status"
      options:
        - "Open"
        - "Mitigation in progress"
        - "Mitigated - Monitoring"
        - "Resolved - Postmortem pending"
        - "Postmortem completed"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      options:
        - "Production"
        - "Pre-Production / Staging"
        - "Test / QA"
        - "Development / Sandbox"
    validations:
      required: true

  # -------------------------------------------------------
  # 2) Scope & Impact (quantify the blast radius)
  # -------------------------------------------------------
  - type: textarea
    id: affected_scope
    attributes:
      label: "Affected Products / Services / Tenants"
      placeholder: |
        - Products:
        - Services/components:
        - Tenants/customers:
        - Regions:
        - Entry points (API/URL/jobs):
    validations:
      required: true

  - type: textarea
    id: customer_impact
    attributes:
      label: "Customer Impact (business terms)"
      placeholder: |
        What could/couldn’t users do?
        Approx affected tenants/users:
        What was the customer-facing symptom?
        Workaround available? (Y/N) If yes, what?
    validations:
      required: true

  - type: textarea
    id: impact_quantification
    attributes:
      label: "Impact Quantification (if available)"
      description: "Enough to reason about severity + SLO impact."
      placeholder: |
        - Duration of impact (minutes):
        - Error rate (%):
        - Failed requests (#):
        - Latency impact (p95/p99):
        - Revenue/ops impact estimate:
    validations:
      required: false

  # -------------------------------------------------------
  # 3) Detection & Response Times (MTTA/MTTR inputs)
  # -------------------------------------------------------
  - type: dropdown
    id: detected_by
    attributes:
      label: "Detection Source"
      options:
        - "Monitoring / Alerting"
        - "Internal user (staff)"
        - "Customer report"
        - "Automated test / synthetic checks"
        - "Other"
    validations:
      required: true

  - type: input
    id: started_at
    attributes:
      label: "Estimated Start Time (UTC)"
      placeholder: "2026-02-25T14:00:00Z"
    validations:
      required: false

  - type: input
    id: first_detected_at
    attributes:
      label: "First Detected (UTC)"
      placeholder: "2026-02-25T14:25:00Z"
    validations:
      required: true

  - type: input
    id: acknowledged_at
    attributes:
      label: "Acknowledged (UTC)"
      description: "When on-call/IC acknowledged the incident."
      placeholder: "2026-02-25T14:27:00Z"
    validations:
      required: false

  - type: input
    id: mitigated_at
    attributes:
      label: "Mitigated At (UTC)"
      description: "When customer impact was stopped/reduced (even if not fully fixed)."
      placeholder: "2026-02-25T14:45:00Z"
    validations:
      required: false

  - type: input
    id: resolved_at
    attributes:
      label: "Fully Resolved At (UTC)"
      placeholder: "2026-02-25T15:10:00Z"
    validations:
      required: false

  # -------------------------------------------------------
  # 4) Roles, Ownership, Communication
  # -------------------------------------------------------
  - type: input
    id: incident_commander
    attributes:
      label: "Incident Commander (IC)"
      placeholder: "@oncall-sre"
    validations:
      required: true

  - type: input
    id: primary_oncall
    attributes:
      label: "Primary On-Call / Ops Engineer"
      placeholder: "@svc-owner"
    validations:
      required: true

  - type: input
    id: comms_owner
    attributes:
      label: "Comms Owner (internal/external updates)"
      placeholder: "@support-lead"
    validations:
      required: false

  - type: textarea
    id: comms_log
    attributes:
      label: "Customer / Stakeholder Communications Log"
      description: "What was communicated, where, and when."
      placeholder: |
        - 14:30Z — Internal #incidents update:
        - 14:40Z — Customer status page update:
        - Next update scheduled:
    validations:
      required: false

  # -------------------------------------------------------
  # 5) Timeline (UTC) + Decision Log
  # -------------------------------------------------------
  - type: textarea
    id: timeline
    attributes:
      label: "Incident Timeline (UTC)"
      placeholder: |
        - 14:00Z — Impact started (estimated)
        - 14:25Z — Alert fired
        - 14:27Z — Acknowledged
        - 14:35Z — Hypothesis formed
        - 14:40Z — Mitigation applied (rollback/flag/scale)
        - 14:45Z — Impact mitigated
        - 15:10Z — Root cause fix deployed
        - 15:30Z — Stable monitoring window complete
    validations:
      required: true

  - type: textarea
    id: decision_log
    attributes:
      label: "Decision Log (why we chose rollback/flag/scale/etc.)"
      placeholder: |
        - Decision:
          Reason:
          Alternatives considered:
          Risks:
    validations:
      required: false

  # -------------------------------------------------------
  # 6) Technical Context & Evidence
  # -------------------------------------------------------
  - type: textarea
    id: alert_refs
    attributes:
      label: "Alert & Monitoring References"
      placeholder: |
        Alerts:
        Dashboards (Grafana):
        Logs queries:
        Traces queries:
    validations:
      required: false

  - type: input
    id: correlation_id
    attributes:
      label: "Correlation / Request IDs (if applicable)"
      placeholder: "x-request-id: 12ab34cd"
    validations:
      required: false

  - type: textarea
    id: current_status
    attributes:
      label: "Current Status & Mitigation Summary"
      placeholder: |
        Current system state:
        Temporary mitigations in place:
        Residual risk / degraded modes:
        What we are monitoring:
    validations:
      required: true

  - type: textarea
    id: suspected_root_cause
    attributes:
      label: "Suspected Root Cause (initial)"
      placeholder: |
        Early hypothesis:
        Suspected components:
        Related recent changes:
    validations:
      required: false

  - type: textarea
    id: contributing_factors
    attributes:
      label: "Contributing Factors"
      placeholder: |
        Technical:
        Operational:
        Process/communication:
    validations:
      required: false

  - type: textarea
    id: logs_and_diagnostics
    attributes:
      label: "Logs & Diagnostics (sanitized)"
      render: shell
      placeholder: |
        Logs:
        Traces:
        HTTP failures:
        DB errors:
        Resource saturation:
    validations:
      required: false

  - type: textarea
    id: infra_changes
    attributes:
      label: "Recent Changes (code/infra/config) around incident window"
      placeholder: |
        Deployments (svc/version/sha/time):
        Infra changes (k8s/db/network):
        Feature flag flips:
        Migrations:
    validations:
      required: false

  # -------------------------------------------------------
  # 7) Mitigation vs Resolution (separate clearly)
  # -------------------------------------------------------
  - type: textarea
    id: mitigation_steps
    attributes:
      label: "Mitigation Steps (stop the bleeding)"
      placeholder: |
        - Rollback:
        - Disable flag:
        - Scale up/out:
        - Rate limit / circuit breaker:
        - Traffic reroute:
    validations:
      required: false

  - type: textarea
    id: resolution_details
    attributes:
      label: "Resolution Details (root-cause fix) + Validation"
      placeholder: |
        Root-cause fix implemented:
        Checks/tests run:
        Validation steps:
        Monitoring window:
    validations:
      required: false

  - type: textarea
    id: verification
    attributes:
      label: "Recovery Verification"
      description: "How we proved recovery (not just 'it looks fine')."
      placeholder: |
        - Metrics returned to baseline:
        - Synthetic checks passing:
        - Error rate normalized:
        - Customer confirmation (if any):
    validations:
      required: false

  # -------------------------------------------------------
  # 8) SLO/SLA & Error Budget Accounting
  # -------------------------------------------------------
  - type: textarea
    id: slo_impact
    attributes:
      label: "SLO / SLA Impact"
      placeholder: |
        SLOs affected:
        SLI during incident window:
        Error budget consumed:
        SLA breach? (Y/N):
    validations:
      required: false

  - type: textarea
    id: metrics_impact
    attributes:
      label: "Metrics & Observability Notes"
      placeholder: |
        Traffic patterns:
        Latency/error spikes:
        Resource saturation:
        Notable correlations:
    validations:
      required: false

  # -------------------------------------------------------
  # 9) Follow-ups (prevention, detection, response)
  # -------------------------------------------------------
  - type: textarea
    id: follow_up_actions
    attributes:
      label: "Follow-up Actions / Action Items"
      description: "Make these atomic. Prefer linking to tasks/bugs with owners."
      placeholder: |
        Prevention:
        - [ ] ...

        Detection:
        - [ ] ...

        Response/runbooks:
        - [ ] ...

        Governance/quality:
        - [ ] Create tasks/bugs:
    validations:
      required: false

  - type: dropdown
    id: postmortem_required
    attributes:
      label: "Postmortem Required?"
      options:
        - "Yes — SEV0/SEV1 or repeated SEV2"
        - "Recommended"
        - "No"
    validations:
      required: true

  - type: input
    id: postmortem_due
    attributes:
      label: "Postmortem Due Date (UTC)"
      placeholder: "2026-03-02"
    validations:
      required: false

  # -------------------------------------------------------
  # 10) Governance & Traceability
  # -------------------------------------------------------
  - type: textarea
    id: governance_links
    attributes:
      label: "Related Issues / Changes / Governance Items"
      placeholder: |
        Bugs:
        Tasks:
        PRs/Deploys:
        Requirements (REQ-*):
        Test cases (TC-*):
        ADRs:
        RTM rows:
    validations:
      required: false

  - type: textarea
    id: runbooks_and_docs
    attributes:
      label: "Runbooks & Documentation"
      placeholder: |
        Runbooks used:
        Runbook worked? (Y/N) Gaps:
        Docs to update:
    validations:
      required: false

  - type: input
    id: reporter
    attributes:
      label: "Incident Reporter"
      placeholder: "@oncall-sre"
    validations:
      required: true

  # -------------------------------------------------------
  # 11) Preflight
  # -------------------------------------------------------
  - type: checkboxes
    id: preflight
    attributes:
      label: "Pre-Flight Checklist"
      options:
        - label: "Impact and severity are clear and quantified where possible."
          required: true
        - label: "Timeline includes at least detect/ack/mitigate/resolved (best-effort)."
          required: true
        - label: "Logs and evidence are sanitized (no secrets/PII)."
          required: true
        - label: "Mitigation is separated from root-cause resolution."
          required: true
        - label: "Follow-up actions are listed or linked."
          required: false