name: "📘 RFC — Request for Comments"
description: "Propose a significant design, architectural change, platform capability, or organizational process improvement."
title: "[RFC] <short summary>"
labels:
  - "type:rfc"
  - "architecture"
  - "design"
  - "triage"

body:
  - type: markdown
    attributes:
      value: |
        # 📘 Request for Comments (RFC)

        RFCs are used for:
        - Architecture changes or new architectural patterns  
        - Platform-wide initiatives (BrikByteOS, pipelines, SREOps, QAOps, etc.)  
        - Major product or system changes  
        - Infrastructure, CI/CD, security, or observability redesigns  
        - Governance changes that require broad consensus  
        - Any change that will result in an ADR once approved  

        This template captures **motivation, context, options, risks, governance, and traceability**.

        > 🔐 **Do not include secrets, credentials, or sensitive personal data.**

  # --- Summary & Context ---
  - type: input
    id: summary
    attributes:
      label: "RFC Summary"
      description: "Short, clear description summarizing the intent of the RFC."
      placeholder: "e.g., Introduce unified Feature Flag Lifecycle Governance across all BrikByte products."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context & Background"
      description: "Explain the background, current situation, and why the RFC is necessary."
      placeholder: |
        - What problem or gap exists?
        - What is the current system/process?
        - Why now? (timing, incidents, growth, scalability, etc.)
    validations:
      required: true

  # --- Problem Statement ---
  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem Statement"
      description: "Define the problem clearly and precisely. Do not propose a solution here."
      placeholder: |
        - What is broken or suboptimal?
        - Who is affected and how?
        - What constraints or limitations exist?
    validations:
      required: true

  # --- Goals & Non-Goals ---
  - type: textarea
    id: goals
    attributes:
      label: "Goals (What This RFC Intends to Achieve)"
      description: "Describe the objectives of this RFC."
      placeholder: |
        - Standardize X
        - Support Y capability
        - Improve Z metric (availability, latency, governance, etc.)
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: "Non-Goals (What This RFC Will NOT Do)"
      description: "Clarify explicit boundaries to avoid scope creep."
      placeholder: |
        - This RFC does NOT redesign...
        - This RFC does NOT change...
    validations:
      required: false

  # --- Proposal / Design ---
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Design / Solution"
      description: "Describe the proposed design or approach in detail."
      placeholder: |
        Include:
        - Architecture or system design
        - API updates (if any)
        - Data model changes
        - CI/CD impacts
        - Feature flags
        - Security & compliance considerations
        - Interaction with other systems
    validations:
      required: true

  - type: textarea
    id: diagrams
    attributes:
      label: "Architecture Diagrams / Flows (optional)"
      description: "Paste links to diagrams, sketches, Figma boards, or draw.io exports."
      placeholder: |
        - High-level architecture:
        - Sequence diagrams:
        - Data flows:
    validations:
      required: false

  # --- Alternatives ---
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "List evaluated alternatives and explain why they were not selected."
      placeholder: |
        Alternative 1:
        - Pros:
        - Cons:

        Alternative 2:
        - Pros:
        - Cons:
    validations:
      required: true

  # --- Impact ---
  - type: textarea
    id: impact_analysis
    attributes:
      label: "Impact Analysis"
      description: "Describe the impact of this RFC on systems, teams, processes, and customers."
      placeholder: |
        - Affected services / modules:
        - DevOps / CI/CD impact:
        - QA / TestOps impact:
        - SRE impact (SLOs, error budgets, incident response):
        - Compliance / security impact:
        - DocsOps updates:
    validations:
      required: true

  # --- Migration / Rollout Plan ---
  - type: textarea
    id: rollout_plan
    attributes:
      label: "Migration / Rollout Strategy"
      description: "Describe how this RFC will be rolled out safely and incrementally."
      placeholder: |
        - Feature flag gating
        - Backward-compatibility strategy
        - Incremental rollout phases
        - Data migration plan
        - Rollback plan
    validations:
      required: true

  # --- Risks & Mitigations ---
  - type: textarea
    id: risks
    attributes:
      label: "Risks & Mitigations"
      description: "List technical, organizational, and operational risks with mitigation strategies."
      placeholder: |
        - Risk:
        - Probability:
        - Impact:
        - Mitigation:
    validations:
      required: true

  # --- Governance & Traceability ---
  - type: textarea
    id: governance
    attributes:
      label: "Governance & Traceability (BrikByteOS)"
      description: "List all governance items this RFC relates to or requires changes for."
      placeholder: |
        - ADR to create: ADR-00X
        - Related policies (GOV-POLICY-*):
        - REQ-* to update:
        - Test cases (TC-*):
        - RTM rows affected:
        - CI/Rulesets:
    validations:
      required: false

  # --- Dependencies ---
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies & Blockers"
      description: "List upstream or downstream dependencies."
      placeholder: |
        - Blocks:
        - Depends on:
        - Cross-team coordination required:
    validations:
      required: false

  # --- Success Metrics ---
  - type: textarea
    id: success_metrics
    attributes:
      label: "Success Metrics"
      description: "How will we know this RFC was successful?"
      placeholder: |
        - Engineering KPIs:
        - SLO improvements:
        - DX improvements:
        - Reduced incidents:
        - Process compliance:
    validations:
      required: false

  # --- Required Reviewers & Approvals ---
  - type: textarea
    id: reviewers
    attributes:
      label: "Required Reviewers / Approvals"
      description: "List the teams or roles required to review and approve this RFC."
      placeholder: |
        - Architecture Review Board (ARB)
        - Platform Lead (Governance)
        - Security Lead (if applicable)
        - SRE
        - QA Lead
        - Product Owner (if cross-cutting)
    validations:
      required: true

  - type: input
    id: reporter
    attributes:
      label: "RFC Author / Reporter"
      description: "Your name or GitHub handle."
      placeholder: "@thapelomagqazana"
    validations:
      required: true

  # --- Pre-flight Checklist ---
  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-Submission Checklist"
      description: "Confirm before submitting this RFC."
      options:
        - label: "Problem, context, and motivation are clearly articulated."
          required: true
        - label: "At least one alternative solution is considered."
          required: true
        - label: "Risks and mitigations are documented."
          required: true
        - label: "Traceability into ADR/Policy/RTM is included (or will be created)."
          required: true
        - label: "No sensitive or personal data is included."
          required: true
