name: "🆘 Support Ticket"
description: "Log a customer support request so it can be triaged into bugs, incidents, or feature work."
title: "[SUPPORT] <short summary>"
labels:
  - "support:customer-issue"
  - "status:triage"

body:
  - type: markdown
    attributes:
      value: |
        This form is for **customer / internal support requests**.

        Capture:
        - Who is affected
        - What they’re experiencing
        - Business impact + urgency
        - Enough evidence for engineering/product to act

        🔐 Do not paste secrets, credentials, or sensitive personal data. Mask before submission.

  # -------------------------------------------------------
  # 1) Requester & Customer Identity
  # -------------------------------------------------------
  - type: input
    id: requester_name
    attributes:
      label: "Requester Name"
      placeholder: "John Doe / Internal: @support-agent"
    validations:
      required: true

  - type: input
    id: requester_contact
    attributes:
      label: "Requester Contact"
      placeholder: "john.doe@example.com, +27..., or Slack handle"
    validations:
      required: false

  - type: input
    id: customer_account
    attributes:
      label: "Customer / Tenant / Account"
      placeholder: "Tenant: ACME Logistics • Region: ZA"
    validations:
      required: true

  - type: dropdown
    id: request_channel
    attributes:
      label: "Request Channel"
      options:
        - "Email"
        - "Support Portal"
        - "Phone"
        - "WhatsApp"
        - "Slack / Internal"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: data_sensitivity
    attributes:
      label: "Data Sensitivity (handling)"
      description: "Controls how we share logs/screenshots and who can access the ticket."
      options:
        - "None / General"
        - "Non-PII data (operational)"
        - "PII present (mask required)"
        - "Financial/Billing sensitive"
        - "Regulated (POPIA/GDPR/contractual)"
    validations:
      required: true

  # -------------------------------------------------------
  # 2) Classification & Urgency (customer vs internal)
  # -------------------------------------------------------
  - type: dropdown
    id: request_type
    attributes:
      label: "Request Type"
      options:
        - "Question / How-to"
        - "Bug / Something is broken"
        - "Access / Account issue"
        - "Data issue (missing/incorrect/non-PII)"
        - "Billing / Invoicing"
        - "Feature request / Enhancement"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: "Urgency (Customer View)"
      options:
        - "Critical — Cannot work / system unusable"
        - "High — Major disruption / no workaround"
        - "Medium — Some disruption / workaround exists"
        - "Low — Minor issue / general query"
    validations:
      required: true

  - type: dropdown
    id: internal_priority
    attributes:
      label: "Internal Priority (Support Triage)"
      description: "How we prioritize internally (separate from customer tone)."
      options:
        - "P0 — Potential incident / many users / major revenue risk"
        - "P1 — Core workflow blocked (single customer/tenant)"
        - "P2 — Degraded workflow / workaround exists"
        - "P3 — Question / minor / backlog"
    validations:
      required: true

  - type: dropdown
    id: ticket_status
    attributes:
      label: "Ticket Status"
      options:
        - "New"
        - "Investigating"
        - "Waiting on Customer"
        - "Escalated"
        - "Resolved"
        - "Closed"
    validations:
      required: true

  - type: textarea
    id: business_impact
    attributes:
      label: "Business Impact"
      placeholder: |
        Business process blocked:
        Approx affected users:
        Deadline / time sensitivity:
        Financial impact (if known):
    validations:
      required: true

  # -------------------------------------------------------
  # 3) Product Context
  # -------------------------------------------------------
  - type: input
    id: product_area
    attributes:
      label: "Product / Module / Repo"
      description: "Use proj/* and area:* taxonomy where possible."
      placeholder: "CargoPulse Web • proj/cargopulse • area:shipments"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      options:
        - "Production"
        - "Staging / UAT"
        - "Test / QA"
        - "Unknown / Not specified"
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: "Version / Build (if known)"
      placeholder: "v1.4.2 (web) / Android v1.0.3"
    validations:
      required: false

  - type: input
    id: client_platform
    attributes:
      label: "Client Platform (if known)"
      placeholder: "Chrome 122 Windows 11 / Safari iOS / Android"
    validations:
      required: false

  # -------------------------------------------------------
  # 4) The Ask (customer voice) + Evidence
  # -------------------------------------------------------
  - type: input
    id: summary
    attributes:
      label: "Short Summary (customer POV)"
      placeholder: "Unable to upload documents to shipment record."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Full Description (customer words if possible)"
      placeholder: |
        Customer says:
        Support clarification:
        What changed recently (if they know):
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce (if bug-like)"
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: "Expected vs Actual"
      placeholder: |
        Expected:
        Actual:
    validations:
      required: false

  - type: textarea
    id: attachments
    attributes:
      label: "Screenshots / Attachments / Recording Links"
      placeholder: "Drag-and-drop images here or paste Loom/file links."
    validations:
      required: false

  # -------------------------------------------------------
  # 5) Support Investigation (containment + routing)
  # -------------------------------------------------------
  - type: textarea
    id: diagnostics
    attributes:
      label: "Support Diagnostics Performed"
      placeholder: |
        Checks performed:
        Reproduced? (Y/N) How:
        Logs checked? (where/what query):
        Status page checked?:
        Similar tickets found?:
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: "Workaround / Mitigation Provided"
      description: "Support-first: what can the customer do right now?"
      placeholder: |
        Workaround steps:
        Temporary configuration:
        Feature flag toggle (if any):
        Customer guidance:
    validations:
      required: false

  - type: dropdown
    id: suspected_routing
    attributes:
      label: "Suggested Routing (next destination)"
      options:
        - "Support team investigation"
        - "Engineering — potential bug"
        - "SRE — potential incident"
        - "Product — potential feature request"
        - "Billing / Finance"
        - "Access / Identity"
        - "Unsure / Needs triage"
    validations:
      required: true

  - type: textarea
    id: escalation_readiness
    attributes:
      label: "Escalation Readiness (what we have / what’s missing)"
      description: "Make escalation cheap: list what’s ready and what must still be collected."
      placeholder: |
        Collected:
        - Tenant/customer:
        - Environment/version:
        - Repro steps:
        - Evidence:

        Missing (to request from customer):
        - Time observed:
        - Screenshots:
        - Error messages:
        - Request IDs:
    validations:
      required: false

  # -------------------------------------------------------
  # 6) Internal Links & SLA
  # -------------------------------------------------------
  - type: textarea
    id: internal_links
    attributes:
      label: "Related Internal Items"
      placeholder: |
        Bug:
        Incident:
        Feature request:
        GOV/Policy:
    validations:
      required: false

  - type: input
    id: sla_or_deadline
    attributes:
      label: "SLA / Deadline"
      placeholder: "Response in 4 business hours / go-live 2026-03-01"
    validations:
      required: false

  - type: textarea
    id: customer_message_draft
    attributes:
      label: "Customer Reply Draft (optional)"
      description: "A ready-to-send response improves speed and consistency."
      placeholder: |
        Acknowledgement:
        What we’re doing:
        What we need from them:
        Next update time:
    validations:
      required: false

  # -------------------------------------------------------
  # 7) Metadata & Preflight
  # -------------------------------------------------------
  - type: input
    id: support_agent
    attributes:
      label: "Support Agent"
      placeholder: "@support-agent"
    validations:
      required: true

  - type: checkboxes
    id: preflight
    attributes:
      label: "Pre-Flight Checklist"
      options:
        - label: "Customer identity/tenant + environment are captured."
          required: true
        - label: "Impact and urgency reflect the customer’s reality."
          required: true
        - label: "Workaround/mitigation is included if known."
          required: false
        - label: "No secrets/credentials/PII are included (or they are masked)."
          required: true
        - label: "Suggested routing is selected."
          required: true