name: "🧰 Task / Work Item"
description: "Plan, implement, and govern a concrete engineering work item."
title: "[TASK] <concise, action-oriented summary>"
labels:
  - "type:task"
  - "status:triage"

body:
  - type: markdown
    attributes:
      value: |
        👋 Welcome to BrikByte Studios Engineering.

        Use this template for **well-scoped, sprint-sized work items**:
        - Feature slices, bug fixes, refactors, platform improvements, enablement work

        ❗ If this item exceeds **5 days**, split it or create an Epic.

        🔐 Do not include secrets, credentials, or personal data.

  # --- Executive Summary ---
  - type: textarea
    id: summary
    attributes:
      label: "Task Summary"
      description: "One-paragraph executive summary."
      placeholder: |
        What is being done?
        Why is it needed?
        What outcome is expected?
    validations:
      required: true

  # --- Classification ---
  - type: dropdown
    id: task_type
    attributes:
      label: "Work Classification (type:*)"
      options:
        - "type:feature"
        - "type:improvement"
        - "type:bug"
        - "type:refactor"
        - "type:chore"
        - "type:spike"
        - "type:docs"
        - "type:test"
        - "type:governance"
      default: 0
    validations:
      required: true

  - type: input
    id: project
    attributes:
      label: "Project / Platform (proj/*)"
      placeholder: "proj/brikbyteos, proj/cargopulse"
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: "Primary Domain / Area (area:*)"
      placeholder: "area:auth, area:ci-cd, area:billing"
    validations:
      required: true

  - type: input
    id: phase
    attributes:
      label: "Delivery Phase (phase/*)"
      placeholder: "phase/foundation, phase/hardening"
    validations:
      required: false

  # --- Priority & Sizing ---
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "P0 — Production Blocker"
        - "P1 — Critical"
        - "P2 — Important"
        - "P3 — Nice-to-have"
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: "Estimated Size"
      options:
        - "XS (≤1 day)"
        - "S (1–2 days)"
        - "M (2–3 days)"
        - "L (3–5 days)"
        - "XL (>5 days — split)"
    validations:
      required: false

  # --- Ownership ---
  - type: input
    id: owner
    attributes:
      label: "Primary Owner"
      placeholder: "@platform-lead, @qa-team"
    validations:
      required: false

  - type: input
    id: reporter
    attributes:
      label: "Reporter"
      placeholder: "@thapelomagqazana"
    validations:
      required: true

  # --- Parent & Traceability ---
  - type: dropdown
    id: parent_type
    attributes:
      label: "Work Hierarchy"
      options:
        - "Standalone"
        - "Epic"
        - "Feature"
        - "Defect"
        - "Governance"
      default: 0
    validations:
      required: true

  - type: input
    id: parent_ref
    attributes:
      label: "Parent Reference"
      placeholder: "#123, EPIC-004"
    validations:
      required: false

  # --- Outcome Definition ---
  - type: textarea
    id: objective
    attributes:
      label: "Outcome / Objective"
      placeholder: |
        After this task:
        - What will be measurably better?
        - What risk is reduced?
        - What capability is added?
    validations:
      required: true

  - type: textarea
    id: success_metrics
    attributes:
      label: "Success Criteria / KPIs"
      placeholder: |
        - Latency < X ms
        - Error rate < Y%
        - Coverage ≥ Z%
        - Manual steps eliminated
    validations:
      required: false

  # --- Context ---
  - type: textarea
    id: context
    attributes:
      label: "Context & Background"
      placeholder: |
        Current state
        Constraints
        Related incidents
        Prior attempts
    validations:
      required: false

  # --- Deliverables ---
  - type: textarea
    id: deliverables
    attributes:
      label: "Deliverables"
      placeholder: |
        - [ ] Code merged
        - [ ] Tests added
        - [ ] Docs updated
        - [ ] Dashboards created
    validations:
      required: true

  # --- Test Plan / Scenarios (NEW) ---
  - type: textarea
    id: test_plan
    attributes:
      label: "Test Plan / Scenarios"
      description: "Describe how this change will be validated (unit/integration/e2e/manual), including key scenarios."
      placeholder: |
        Testing levels:
        - Unit:
        - Integration:
        - E2E:
        - Manual QA / UAT:

        Core scenarios:
        - ✅ Positive: <what should work>
        - ❌ Negative: <what must fail safely>
        - ⚠️ Edge: <boundaries, weird inputs>
        - 🧨 Corner: <rare combinations>

        Non-functional (if relevant):
        - Security:
        - Performance:
        - Reliability / rollback verification:

        Evidence:
        - Link to TC IDs / test files / run logs
    validations:
      required: true

  # --- Definition of Done ---
  - type: textarea
    id: dod
    attributes:
      label: "Definition of Done"
      placeholder: |
        - [ ] CI green
        - [ ] Review approved
        - [ ] Test Plan executed (evidence attached)
        - [ ] Monitoring/alerts updated (if relevant)
        - [ ] Evidence archived
    validations:
      required: false

  # --- Technical Design ---
  - type: textarea
    id: technical_plan
    attributes:
      label: "Technical Approach"
      placeholder: |
        Architecture
        Affected services
        APIs
        Data changes
        Migration strategy
    validations:
      required: false

  # --- Dependencies ---
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies (rel/*)"
      placeholder: |
        rel/depends-on: #234
        rel/blocks: #456
    validations:
      required: false

  # --- Governance ---
  - type: textarea
    id: governance
    attributes:
      label: "Governance & Compliance"
      placeholder: |
        ADRs
        Policies
        RTM
        Audit refs
    validations:
      required: false

  # --- Risk Management ---
  - type: textarea
    id: risks
    attributes:
      label: "Risks & Failure Modes"
      placeholder: |
        Technical
        Product
        Operational
        Security
    validations:
      required: false

  - type: textarea
    id: mitigations
    attributes:
      label: "Mitigation & Rollback Plan"
      placeholder: |
        Feature flags
        Canary
        Rollback steps
        Observability hooks
    validations:
      required: false

  # --- Delivery Planning ---
  - type: input
    id: milestone
    attributes:
      label: "Target Milestone / Sprint"
      placeholder: "Sprint-2026-02, v2.1.0"
    validations:
      required: false

  - type: input
    id: estimate
    attributes:
      label: "Numeric Estimate"
      placeholder: "5 pts, 12h"
    validations:
      required: false

  # --- Evidence ---
  - type: textarea
    id: evidence
    attributes:
      label: "Evidence & Artefacts"
      placeholder: |
        PR:
        Logs:
        Screenshots:
        Benchmarks:
        Test run links:
    validations:
      required: false

  - type: input
    id: implementation_ref
    attributes:
      label: "PR / Commit"
      placeholder: "#456, abc123"
    validations:
      required: false

  # --- Future Enhancements (Out of Scope) ---
  - type: textarea
    id: future_enhancements
    attributes:
      label: "Future Enhancements / Expansion (Out of Scope)"
      description: "Capture follow-up improvements or architectural evolutions intentionally excluded from this task."
      placeholder: |
        🚀 Potential Enhancements:
        - Performance scaling improvements
        - Horizontal scaling support
        - Multi-region readiness
        - Extended validation rules

        🧠 Architectural Evolution:
        - Extract to shared module
        - Convert to event-driven architecture
        - Add caching layer

        📊 Product Extensions:
        - Expose via public API
        - Add dashboard metrics

        📌 If large, create Epic and reference here.
    validations:
      required: false

  # --- Preflight ---
  - type: checkboxes
    id: preflight
    attributes:
      label: "Preflight Validation"
      options:
        - label: "Scope is clearly defined"
          required: true
        - label: "Task is sprint-sized"
          required: true
        - label: "Dependencies identified"
          required: true
        - label: "Test plan/scenarios are included"
          required: true
        - label: "No sensitive data included"
          required: true
