# ==============================================================================
# BrikByteOS — .NET Dependency Cache (NuGet)
#
# Action: BrikByte-Studios/.github/.github/actions/cache-dotnet-deps
#
# Purpose:
#   - Detects .NET project/solution under a given project-path.
#   - If found, caches:
#       • Global NuGet packages: ~/.nuget/packages
#       (optionally extend to tools in future: ~/.dotnet/tools)
#   - Cache key includes:
#       • runner.os
#       • dotnet-version
#       • hash of *.sln / *.csproj / *.fsproj / *.vbproj
#
# Usage (in a workflow):
#
#   - name: "Cache .NET dependencies & NuGet artifacts"
#     uses: BrikByte-Studios/.github/.github/actions/cache-dotnet-deps@main
#     with:
#       dotnet-version: "8.0.x"
#       project-path: "dotnet-api-example"
#
# ==============================================================================

name: "Cache .NET Dependencies (NuGet)"
description: >
  BrikByteOS composite action to cache .NET NuGet dependencies based on
  dotnet version + project/solution lock graph (sln/csproj/fsproj/vbproj).

inputs:
  dotnet-version:
    description: ".NET SDK version used in CI (e.g., 6.0.x, 7.0.x, 8.0.x). Used in cache key."
    required: true
  project-path:
    description: >
      Relative path to the .NET project/solution folder (where .sln/.csproj live).
      Defaults to the repository root if not provided.
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1) Detect .NET project/solution & compute cache paths
    # -------------------------------------------------------------------------
    - name: "Detect .NET project/solution"
      id: detect
      shell: bash
      env:
        PROJECT_PATH_INPUT: ${{ inputs.project-path }}
      run: |
        set -euo pipefail

        PROJECT_PATH="${PROJECT_PATH_INPUT:-.}"
        echo "🔍 Inspecting .NET project at: ${PROJECT_PATH}"

        if [ ! -d "${PROJECT_PATH}" ]; then
          echo "::notice::.NET cache: PROJECT_PATH '${PROJECT_PATH}' does not exist. Skipping cache."
          echo "has-project=false"        >> "$GITHUB_OUTPUT"
          echo "nuget-cache-paths="       >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Allow empty globs instead of literal patterns.
        shopt -s nullglob

        sln_files=( "${PROJECT_PATH}"/*.sln )
        csproj_files=( "${PROJECT_PATH}"/*.csproj )
        fsproj_files=( "${PROJECT_PATH}"/*.fsproj )
        vbproj_files=( "${PROJECT_PATH}"/*.vbproj )

        has_solution="false"
        has_project="false"

        if [ ${#sln_files[@]} -gt 0 ]; then
          has_solution="true"
        fi

        if [ ${#csproj_files[@]} -gt 0 ] || [ ${#fsproj_files[@]} -gt 0 ] || [ ${#vbproj_files[@]} -gt 0 ]; then
          has_project="true"
        fi

        if [ "${has_solution}" != "true" ] && [ "${has_project}" != "true" ]; then
          echo "::notice::.NET cache: No *.sln or project file found under '${PROJECT_PATH}'. Skipping cache."
          echo "has-project=false"        >> "$GITHUB_OUTPUT"
          echo "nuget-cache-paths="       >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "✅ .NET project files detected under '${PROJECT_PATH}'."
        echo "   Solutions: ${sln_files[*]:-<none>}"
        echo "   Projects : ${csproj_files[*]:-<none>} ${fsproj_files[*]:-<none>} ${vbproj_files[*]:-<none>}"

        # Global NuGet package cache (standard on GitHub-hosted runners).
        NUGET_GLOBAL_PACKAGES="${HOME}/.nuget/packages"
        echo "📦 NuGet global packages cache: ${NUGET_GLOBAL_PACKAGES}"

        echo "has-project=true"                    >> "$GITHUB_OUTPUT"
        echo "nuget-cache-paths=${NUGET_GLOBAL_PACKAGES}" >> "$GITHUB_OUTPUT"

    # -------------------------------------------------------------------------
    # 2) Cache NuGet global packages using actions/cache@v4
    #
    #    Key components:
    #      - runner.os
    #      - dotnet-version
    #      - hash of sln/csproj/fsproj/vbproj (+ optional Directory.Packages.props)
    #
    #    This ensures:
    #      - Different .NET SDK versions do not share caches.
    #      - Dependency graph changes (project changes) invalidate cache.
    # -------------------------------------------------------------------------
    - name: "Cache NuGet packages"
      id: cache-nuget
      if: ${{ steps.detect.outputs.has-project == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.detect.outputs.nuget-cache-paths }}
        key: >
          dotnet-${{ runner.os }}-${{ inputs.dotnet-version }}-${{
            hashFiles(
              '**/*.sln',
              '**/*.csproj',
              '**/*.fsproj',
              '**/*.vbproj',
              '**/Directory.Packages.props'
            )
          }}
        restore-keys: |
          dotnet-${{ runner.os }}-${{ inputs.dotnet-version }}-

    # -------------------------------------------------------------------------
    # 3) Log cache result for observability
    # -------------------------------------------------------------------------
    - name: "Summarize .NET cache result"
      if: ${{ steps.detect.outputs.has-project == 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        if [ "${{ steps.cache-nuget.outputs.cache-hit }}" = "true" ]; then
          echo "✅ .NET NuGet cache HIT (dotnet=${{ inputs.dotnet-version }})"
        else
          echo "ℹ️ .NET NuGet cache MISS (dotnet=${{ inputs.dotnet-version }}) — will upload after restore."
        fi
