name: "BrikByteOS Shard Plan"
description: >
  Generates deterministic shard-map.json for static or dynamic modes.
  Safe-by-default: workflows should fall back to static if this step fails.

inputs:
  mode:
    description: "static|dynamic"
    required: false
    default: "static"
  shard_count:
    description: "Number of shards."
    required: true
  test_type:
    description: "unit|integration|e2e|performance (helps find history under .audit)."
    required: false
    default: ""
  items:
    description: "Comma-separated list of test items (paths/ids)."
    required: false
    default: ""
  items_file:
    description: "Newline-delimited file of items."
    required: false
    default: ""
  history_path:
    description: "Optional explicit history file path."
    required: false
    default: ""
  workdir:
    description: "Working directory used for file-size heuristic."
    required: false
    default: "."
  out_dir:
    description: "Output directory (default out/)."
    required: false
    default: "out"
  audit_root:
    description: "Audit root directory (default .audit/)."
    required: false
    default: ".audit"
  seed:
    description: "Optional deterministic seed (not random)."
    required: false
    default: ""

outputs:
  shard_map_path:
    description: "Path to shard-map.json"
    value: "${{ inputs.out_dir }}/shard-map.json"

runs:
  using: "composite"
  steps:
    - name: "Generate shard map (static/dynamic)"
      id: plan
      shell: bash
      run: |
        set -euo pipefail

        PLANNER="${{ github.action_path }}/../../scripts/shard-planner.ts"

        ROOT="$GITHUB_WORKSPACE"
        OUT_DIR="${{ inputs.out_dir }}"
        AUDIT_ROOT="${{ inputs.audit_root }}"
        ITEMS_FILE="${{ inputs.items_file }}"

        # Normalize to absolute if provided and not already absolute
        if [[ -n "${ITEMS_FILE}" && "${ITEMS_FILE}" != /* ]]; then
          ITEMS_FILE="${ROOT}/${ITEMS_FILE}"
        fi
        if [[ -n "${OUT_DIR}" && "${OUT_DIR}" != /* ]]; then
          OUT_DIR="${ROOT}/${OUT_DIR}"
        fi
        if [[ -n "${AUDIT_ROOT}" && "${AUDIT_ROOT}" != /* ]]; then
          AUDIT_ROOT="${ROOT}/${AUDIT_ROOT}"
        fi

        echo "[SHARD-PLAN] mode=${{ inputs.mode }}"
        echo "[SHARD-PLAN] shard_count=${{ inputs.shard_count }}"
        echo "[SHARD-PLAN] test_type=${{ inputs.test_type }}"
        echo "[SHARD-PLAN] out_dir=${OUT_DIR}"
        echo "[SHARD-PLAN] items_file=${ITEMS_FILE}"
        echo "[SHARD-PLAN] audit_root=${AUDIT_ROOT}"
        echo "[SHARD-PLAN] planner=${PLANNER}"

        # Guard: file must exist + not empty
        if [[ -n "${ITEMS_FILE}" ]]; then
          if [[ ! -f "${ITEMS_FILE}" ]]; then
            echo "::error::items_file not found: ${ITEMS_FILE}"
            exit 2
          fi
          if [[ ! -s "${ITEMS_FILE}" ]]; then
            echo "::error::items_file is empty: ${ITEMS_FILE}"
            exit 2
          fi
        fi

        if [ ! -f "${PLANNER}" ]; then
          echo "::error::Shard planner not found at ${PLANNER}"
          exit 1
        fi

        mkdir -p "${OUT_DIR}"

        # IMPORTANT:
        # - tsx must be executed via npx so it can transpile TS at runtime
        # - pin node flags to avoid ESM/TS weirdness
        npx -y tsx "${PLANNER}" \
          --mode "${{ inputs.mode }}" \
          --shard-count "${{ inputs.shard_count }}" \
          --test-type "${{ inputs.test_type }}" \
          --items "${{ inputs.items }}" \
          --items-file "${ITEMS_FILE}" \
          --history-path "${{ inputs.history_path }}" \
          --audit-root "${AUDIT_ROOT}" \
          --workdir "${{ inputs.workdir }}" \
          --out-dir "${OUT_DIR}" \
          --seed "${{ inputs.seed }}"

        MAP="${OUT_DIR}/shard-map.json"
        if [ ! -f "${MAP}" ]; then
          echo "::error::Planner finished but did not produce ${MAP}"
          exit 1
        fi

        echo "[SHARD-PLAN] shard-map.json produced at ${MAP}"

    - name: "Export shard plan audit (non-blocking)"
      if: always()
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail

        MAP="${{ inputs.out_dir }}/shard-map.json"
        if [ ! -f "${MAP}" ]; then
          echo "::notice::No shard-map.json produced; skipping audit export."
          exit 0
        fi

        # Put this file INSIDE this action folder:
        # .github/actions/shard-plan/export-parallel-audit.mjs
        EXPORTER="${{ github.action_path }}/export-parallel-audit.mjs"

        if [ ! -f "${EXPORTER}" ]; then
          echo "::warning::Exporter missing at ${EXPORTER}; skipping audit export."
          exit 0
        fi

        echo "[SHARD-PLAN] Exporting audit..."
        node "${EXPORTER}" \
          --shard-map "${MAP}" \
          --audit-root "${{ inputs.audit_root }}"
