name: "Capture E2E Diagnostics to .audit"
description: >
  "Normalizes E2E failure diagnostics (console, network, trace, DOM snapshot)
  into .audit/YYYY-MM-DD/e2e/diagnostics with stable filenames and metadata."

inputs:
  runner:
    description: "playwright|cypress|selenium"
    required: true
  browser:
    description: "chromium|chrome|firefox|webkit|edge|..."
    required: true
  status:
    description: "GitHub job.status (success|failure|cancelled) or BrikByte (success|failed)"
    required: true

  # Optional overrides
  audit_date:
    description: "YYYY-MM-DD (default: computed)"
    required: false
    default: ""
  audit_root:
    description: "Override diagnostics root (default: .audit/<date>/e2e/diagnostics)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Setup Node (for diagnostics capturer)"
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: "Run diagnostics capturer (never fatal)"
      shell: bash
      env:
        E2E_RUNNER: ${{ inputs.runner }}
        E2E_BROWSER: ${{ inputs.browser }}
        E2E_STATUS_RAW: ${{ inputs.status }}
        E2E_AUDIT_DATE: ${{ inputs.audit_date }}
        E2E_DIAG_ROOT: ${{ inputs.audit_root }}

        # Optional metadata enrichment (safe values only)
        GIT_SHA: ${{ github.sha }}
        RUN_ID: ${{ github.run_id }}
        RUN_ATTEMPT: ${{ github.run_attempt }}
        REPO: ${{ github.repository }}
        REF: ${{ github.ref }}
        WORKFLOW: ${{ github.workflow }}
        JOB: ${{ github.job }}
      run: |
        set -euo pipefail
        node "${GITHUB_ACTION_PATH}/capture-e2e-diagnostics.mjs" || true
