name: "BrikByte Policy Gate"
description: "Aggregated governance decision engine (PIPE-GOV-8.1)"

inputs:
  policy_file:
    description: "Effective policy file (JSON or YAML)"
    required: true
    default: "out/effective-policy.json"
  inputs_file:
    description: "Aggregated CI signals JSON (tests, coverage, security, ADR, integrity, meta)"
    required: true
    default: "out/inputs.json"
  waivers_file:
    description: "Optional waivers JSON (normalized per-rule waivers)"
    required: false
    default: "out/waivers.json"
  output_file:
    description: "Path to write decision.json"
    required: false
    default: "out/decision.json"

outputs:
  status:
    description: "Overall decision: passed | passed_with_warnings | failed"
    value: ${{ steps.extract.outputs.status }}
  score:
    description: "Overall numeric governance score (0–100)"
    value: ${{ steps.extract.outputs.score }}

runs:
  using: "composite"
  steps:
    - name: Run policy gate engine
      shell: bash
      run: |
        node scripts/policy/gate-engine.mjs \
          --policy "${{ inputs.policy_file }}" \
          --inputs "${{ inputs.inputs_file }}" \
          --waivers "${{ inputs.waivers_file }}" \
          --out "${{ inputs.output_file }}"

    - name: Extract status/score from decision.json
      id: extract
      shell: bash
      run: |
        status=$(jq -r '.status' "${{ inputs.output_file }}")
        score=$(jq -r '.score' "${{ inputs.output_file }}")
        echo "status=$status" >> "$GITHUB_OUTPUT"
        echo "score=$score" >> "$GITHUB_OUTPUT"
