name: "Selenium Grid Healthcheck"
description: "Waits for Selenium Grid readiness and required browser node registration (Chrome/Firefox/Edge)."

inputs:
  remote_url:
    description: "Remote WebDriver URL (e.g., http://localhost:4444/wd/hub)"
    required: true

  timeout_seconds:
    description: "Max seconds to wait for grid + node registration"
    required: false
    default: "120"

  require_chrome:
    description: "Require at least 1 Chrome node (true/false)"
    required: false
    default: "true"

  require_firefox:
    description: "Require at least 1 Firefox node (true/false)"
    required: false
    default: "true"

  require_edge:
    description: "Require at least 1 Edge node (true/false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Selenium Grid readiness + node registration"
      shell: bash
      run: |
        set -euo pipefail
        chmod +x "${GITHUB_ACTION_PATH}/selenium-grid-healthcheck.sh"

        # Pass inputs explicitly to avoid reliance on env state.
        "${GITHUB_ACTION_PATH}/selenium-grid-healthcheck.sh" \
          --remote-url "${{ inputs.remote_url }}" \
          --timeout-seconds "${{ inputs.timeout_seconds }}" \
          --require-chrome "${{ inputs.require_chrome }}" \
          --require-firefox "${{ inputs.require_firefox }}" \
          --require-edge "${{ inputs.require_edge }}"
