name: Reuse - Container Build & Push

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
        description: "Image/repo name (e.g. sample-service)"
      registry:
        type: string
        default: "ghcr.io"
        description: "Registry hostname (ghcr.io|…)"
      build-context:
        type: string
        default: "."
      dockerfile:
        type: string
        default: "Dockerfile"
      tags:
        type: string
        default: "latest" # comma-separated list supported by buildx
    secrets:
      registry_username:
        required: false
      registry_password:
        required: false

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ${{ inputs.registry }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Normalize owner & image to lowercase (via bash), expose as outputs
      - name: Normalize names
        id: normenv
        shell: bash
        env:
          IMAGE_IN: ${{ inputs['image-name'] }}
        run: |
          set -euo pipefail
          # OWNER from default env var provided by Actions
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
          # Image name from input
          img="${IMAGE_IN,,}"
          echo "image_lc=${img}" >> "$GITHUB_OUTPUT"

      # Login for GHCR using GITHUB_TOKEN
      - name: Login (GHCR)
        if: ${{ env.REGISTRY == 'ghcr.io' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login for custom registry
      - name: Login (custom registry)
        if: ${{ env.REGISTRY != 'ghcr.io' }}
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REG_USER: ${{ secrets.registry_username }}
          REG_PASS: ${{ secrets.registry_password }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${REG_USER:-}" ] && [ -n "${REG_PASS:-}" ]; then
            echo "Logging into ${REGISTRY}"
            echo "${REG_PASS}" | docker login "${REGISTRY}" -u "${REG_USER}" --password-stdin
          else
            echo "No custom registry credentials provided; skipping login."
          fi

      # Normalize tags (lowercase, trim, split commas → newline)
      - name: Normalize tags
        id: norm
        shell: bash
        env:
          INPUT_TAGS: ${{ inputs.tags }}
        run: |
          set -euo pipefail
          T="$(printf '%s' "${INPUT_TAGS}" | tr '[:upper:]' '[:lower:]')"
          T="$(printf '%s' "${T}" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed '/^$/d')"
          echo "list<<EOF" >> "$GITHUB_OUTPUT"
          echo "${T}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs['build-context'] }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.normenv.outputs.owner_lc }}/${{ steps.normenv.outputs.image_lc }}:${{ steps.norm.outputs.list }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ steps.normenv.outputs.owner_lc }}/${{ steps.normenv.outputs.image_lc }}:cache
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ steps.normenv.outputs.owner_lc }}/${{ steps.normenv.outputs.image_lc }}:cache,mode=max
          provenance: true
