name: Reuse - Container Build & Push

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
        description: "Image/repo name (e.g. sample-service)"
      registry:
        type: string
        default: "ghcr.io"
        description: "Registry hostname (ghcr.io|…)"
      build-context:
        type: string
        default: "."
      dockerfile:
        type: string
        default: "Dockerfile"
      tags:
        type: string
        default: "latest" # comma-separated list supported by buildx
    secrets:
      registry_username:   # <-- snake_case to avoid hyphen issues
        required: false
      registry_password:
        required: false

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for ghcr.io push with GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Login for GHCR using GITHUB_TOKEN
      - name: Login (GHCR)
        if: ${{ inputs.registry == 'ghcr.io' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login for custom registry; do NOT put secrets in the 'if:' guard
      - name: Login (custom registry)
        if: ${{ inputs.registry != 'ghcr.io' }}
        env:
          REGISTRY: ${{ inputs.registry }}
          REG_USER: ${{ secrets.registry_username }}
          REG_PASS: ${{ secrets.registry_password }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${REG_USER:-}" ] && [ -n "${REG_PASS:-}" ]; then
            echo "Logging into ${REGISTRY}"
            echo "${REG_PASS}" | docker login "${REGISTRY}" -u "${REG_USER}" --password-stdin
          else
            echo "No custom registry credentials provided; skipping login."
          fi

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs['build-context'] }}
          file: ${{ inputs.dockerfile }}
          push: true
          # bracket syntax for hyphenated input key: inputs['image-name']
          tags: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs['image-name'] }}:${{ inputs.tags }}
          cache-from: type=registry,ref=${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs['image-name'] }}:cache
          cache-to:   type=registry,ref=${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs['image-name'] }}:cache,mode=max
