name: Reuse - Release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: "Release tag (e.g. v1.2.3)"
      changelog:
        type: boolean
        default: true
        description: "Generate GitHub Release notes via GH API"
      registry:
        type: string
        default: "ghcr"
        description: "Reserved for future use: ghcr|acr|ecr"
    secrets:
      token:
        required: false
        description: "Optional PAT; defaults to GITHUB_TOKEN"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create tags and releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag (idempotent) and push
        env:
          GITHUB_TOKEN: ${{ secrets.token != '' && secrets.token || secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ inputs.tag }}"

          # ensure we are on default branch ref
          git fetch --tags --force

          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping creation."
          else
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi

      - name: Generate GitHub Release (auto-notes)
        if: ${{ inputs.changelog }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.token != '' && secrets.token || secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          draft: false
          prerelease: false
