name: Reuse • Container Build&Push
on:
  workflow_call:
    inputs:
      image-name:   { type: string,  required: true }
      registry:     { type: string,  default: "ghcr.io" }
      build-context:{ type: string,  default: "." }
      dockerfile:   { type: string,  default: "Dockerfile" }
      tags:         { type: string,  default: "latest" }  # comma-separated
    secrets:
      registry-username: { required: false }
      registry-password: { required: false }
jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login
        if: ${{ inputs.registry == 'ghcr.io' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs['build-context'] }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tags }}
          cache-from: type=registry,ref=${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}:cache
          cache-to:   type=registry,ref=${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}:cache,mode=max
