name: Reuse • Release
on:
  workflow_call:
    inputs:
      tag:       { type: string, required: true }
      changelog: { type: boolean, default: true }
      registry:  { type: string, default: "ghcr", description: "ghcr|acr|ecr" }
    secrets:
      token: { required: false }
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create tag & release
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          set -euo pipefail
          git tag -a "${{ inputs.tag }}" -m "Release ${{ inputs.tag }}" || true
          git push origin "${{ inputs.tag }}"
      - name: Generate changelog (optional)
        if: ${{ inputs.changelog }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
